name: Revive Lint

on:
    push:
        branches: [ YOUR_BRANCH_NAME ]
    pull_request:

jobs:
  revive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Revive Lint"
        uses: devanoxltd/revive-action@v2
        with:
          args: lint
